Repository calahatras/gitout, pull requests merged in 2021-02, with the labels that each got.

#96 feature(diff): apply basic syntax highlighting for diffed files
  GitOut/Features/Git/Diff/GitDiffControl.xaml.cs
  GitOut/Features/Git/Diff/GitDiffHunk.cs
  GitOut/Features/Git/Diff/HunkLine.cs
  GitOut/Features/Text/CSharpSyntaxHighlighter.cs
  GitOut/Features/Text/CSharpSyntaxHighlighterOptions.cs
  GitOut/Features/Text/IDecoratedMatch.cs
  GitOut/Features/Text/ILineDecorator.cs
  GitOut/Features/Text/ISyntaxHighlighter.cs
  GitOutTest/Features/Text/CSharpSyntaxHighlighterTest.cs
Labels: enhancement, git:diff

#97 simplifies bindings for FileViewVisible
  GitOut/Features/Git/Log/GitLogPage.xaml
Labels: clean

#99 enhancement(shell): back command is now global and subscribed to in NavigationService
  GitOut/Features/Git/Stage/GitStagePage.xaml
  GitOut/Features/Git/Stage/GitStageViewModel.cs
  GitOut/Features/Navigation/INavigationService.cs
  GitOut/Features/Navigation/NavigationService.cs
  GitOut/Features/Settings/SettingsPage.xaml
  GitOut/Features/Settings/SettingsViewModel.cs
  GitOut/Features/Wpf/ApplicationCommands/Navigate.cs
  GitOut/Features/Wpf/CompositeCommand.cs
  GitOut/Features/Wpf/NavigatorShell.xaml
  GitOut/Features/Wpf/NavigatorShellViewModel.cs
Labels: enhancement

#103 fix(diff): revert line numbers in diff control
  GitOut/Features/Git/Diff/GitDiffControl.xaml.cs
Labels: fix

#104 fix(stage): add guard for index in workspace files when changes have been staged
  GitOut/Features/Git/Stage/GitStageViewModel.cs
Labels: fix, git:stage

#98 enhancement(gitlog): add details view for selected commits
  GitOut/Features/Git/Details/GitHistoryEventDetails.xaml
  GitOut/Features/Git/Details/GitHistoryEventDetails.xaml.cs
  GitOut/Features/Git/Log/GitLogPage.xaml
  GitOut/Features/Git/Log/GitLogViewModel.cs
  GitOut/Features/Git/Log/GitTreeEvent.cs
  GitOut/Features/Wpf/Converters/NullToVisibilityMultiConverter.cs
  GitOut/Features/Wpf/CopyTextToClipBoardCommand.cs
  GitOut/Themes/MaterialDesignIcons/MaterialDesignIcons.xaml
Labels: enhancement
